# Generated by Django 3.1.2 on 2020-10-19 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_userinfo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='useranswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=200)),
                ('q2', models.CharField(max_length=200)),
                ('q3', models.CharField(max_length=200)),
                ('q4', models.CharField(max_length=200)),
                ('q5', models.CharField(max_length=200)),
                ('q6', models.CharField(max_length=200)),
                ('q7', models.CharField(max_length=200)),
                ('q8', models.CharField(max_length=200)),
                ('q9', models.CharField(max_length=200)),
                ('q10', models.CharField(max_length=200)),
                ('result', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
