# Generated by Django 3.1.2 on 2020-10-19 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_auto_20201019_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='result',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='quiz',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='question',
            field=models.ManyToManyField(to='quiz.useranswers'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='result',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='userid',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userid',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
