# Generated by Django 3.1.2 on 2020-10-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201019_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
