# Generated by Django 3.1.2 on 2020-10-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('1', '1'), ('0', '0')], default='0', max_length=20),
        ),
    ]
